CREATE TABLE Employee (
  idEmployee INT NOT NULL COMMENT '',
  name VARCHAR(45) NOT NULL COMMENT '',
  role VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (idEmployee)  COMMENT '',
  UNIQUE INDEX idEmployee_UNIQUE (idEmployee ASC)  COMMENT '');

  CREATE TABLE User (
  idUser INT NOT NULL AUTO_INCREMENT COMMENT '',
  email VARCHAR(45) NULL COMMENT '',
  username VARCHAR(45) NOT NULL COMMENT '',
  password VARCHAR(45) NOT NULL COMMENT '',
  num INT NOT NULL COMMENT '',
  PRIMARY KEY (idUser)  COMMENT '',
  UNIQUE INDEX email_UNIQUE (email ASC)  COMMENT '',
  UNIQUE INDEX username_UNIQUE (username ASC)  COMMENT '',
  CONSTRAINT FOREIGN KEY (num)
    REFERENCES Employee (idEmployee) ON DELETE CASCADE
 );

  CREATE TABLE Customer (
  idCustomer INT NOT NULL AUTO_INCREMENT COMMENT '',
  customer VARCHAR(45) NOT NULL COMMENT '',
  coach VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (idCustomer)  COMMENT '',
  UNIQUE INDEX idCustomer_UNIQUE (idCustomer ASC)  COMMENT '');

  CREATE TABLE Class (
  idClass INT NOT NULL AUTO_INCREMENT COMMENT '',
  classname VARCHAR(45) NOT NULL COMMENT '',
  time DATE NOT NULL COMMENT '',
  coach VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (idClass)  COMMENT '',
  UNIQUE INDEX idClass_UNIQUE (idClass ASC)  COMMENT '');

  CREATE TABLE CoachDate (
  idCoachDate INT NOT NULL AUTO_INCREMENT COMMENT '',
  time DATETIME NOT NULL COMMENT '',
  coach VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (idCoachDate)  COMMENT '',
  UNIQUE INDEX idCoachDate_UNIQUE (idCoachDate ASC)  COMMENT '');